spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/admin
    driver-class-name: org.h2.Driver
    username: sa
    password:

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true